steer_angle = [ 1, 0.6, 0.3, 0.15, 0.13, 0.1, 0.08, 0.05 ]	# Maximum steer angles (0.0 - 1.0)
speed_curve = [ 0, 50, 100, 150, 200, 250, 300, 350 ]		# Steering curve, speed to use the steer angles at (KM/H)
steering_speed = 1.0						# Smooth steering speed, akin to Tank Slapper (higher value = faster steering)
countersteering_speed = 4.0					# Multiplier to smooth steering speed when changing steering direction